stages:
  data_process:
    cmd: python source/data_process.py data/telecom_churn.csv
    deps:
    - data/telecom_churn.csv
    - source/data_process.py
    params:
    - data_process.split_ratio
    outs:
    - processed_data
  train:
    cmd: python source/train.py processed_data/out_train.csv
    deps:
    - processed_data/out_train.csv
    - source/train.py
    params:
    - train.class_weight
    - train.max_depth
    - train.min_samples_leaf
    - train.min_samples_split
    - train.n_estimators
    outs:
    - model_dir/model.pkl
