stages:
  data_process:
    cmd: python source/data_process.py data/telecom_churn.csv
    deps:
    - data/telecom_churn.csv
    - source/data_process.py
    params:
    - data_process.split_ratio
    outs:
    - processed_data
  train:
    cmd: python source/train.py processed_data/out_train.csv
    deps:
    - processed_data/out_train.csv
    - source/train.py
    params:
    - train.class_weight
    - train.max_depth
    - train.min_samples_leaf
    - train.min_samples_split
    - train.n_estimators
    outs:
    - model_dir/model.pkl
  evaluate:
    cmd: python source/evaluate.py model_dir/model.pkl processed_data/out_test.csv
    deps:
    - model_dir/model.pkl
    - source/evaluate.py
    outs:
    - results/predictions_vs_actuals.csv
# Copied from DVC live generated yaml
metrics:
- results/live/metrics.json
plots:
- results/live/plots/metrics:
    x: step
- results/live/plots/images
- results/live/plots/sklearn/ROC Curve.json:
    template: simple
    x: fpr
    y: tpr
    title: Receiver operating characteristic (ROC)
    x_label: False Positive Rate
    y_label: True Positive Rate
- results/live/plots/sklearn/Confusion-matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
- results/live/plots/sklearn/Precision-Recall Curve.json:
    template: simple
    x: recall
    y: precision
    title: Precision-Recall Curve
    x_label: Recall
    y_label: Precision
